lab:
  title: IPv6 First Hop Security
  description: 300-410 ENARSI - Implementing Cisco Enterprise Advanced Routing and Services importable CML topology.
  notes: '300-410 ENARSI blueprint lab: IPv6 First Hop Security


    Topics:

    - RA guard

    - DHCPv6 guard

    - ND inspection


    Tasks:

    1. Model rogue RA

    2. Apply first-hop protection

    3. Verify endpoint behavior


    Useful checks:

    - show ip interface brief

    - show running-config

    - show ip route

    - show ip protocols

    - ping and traceroute between endpoints'
  version: 0.2.0
nodes:
- id: n0
  label: EDGE
  node_definition: iosv
  x: 0
  y: -160
  configuration: "hostname EDGE\nno ip domain-lookup\nbanner motd ^C ENARSI IPv6 First Hop Security ^C\ninterface GigabitEthernet0/0\n\
    \ description ENARSI IPv6 First Hop Security\n ip address 198.51.100.2 255.255.255.252\n no shutdown\ninterface GigabitEthernet0/1\n\
    \ description ENARSI IPv6 First Hop Security\n ip address 10.10.10.1 255.255.255.0\n no shutdown\ninterface GigabitEthernet0/2\n\
    \ description ENARSI IPv6 First Hop Security\n ip address 10.10.20.1 255.255.255.0\n no shutdown\nend"
- id: n1
  label: INSIDE-SW
  node_definition: iosvl2
  x: -220
  y: 80
  configuration: "hostname INSIDE-SW\nno ip domain-lookup\nbanner motd ^C ENARSI IPv6 First Hop Security ^C\nvlan 10\n name\
    \ USERS\nvlan 20\n name SERVERS\nvlan 30\n name GUEST\nvlan 99\n name MGMT\ninterface range GigabitEthernet0/1-3\n switchport\
    \ mode access\n spanning-tree portfast\nend"
- id: n2
  label: DMZ-SW
  node_definition: iosvl2
  x: 220
  y: 80
  configuration: "hostname DMZ-SW\nno ip domain-lookup\nbanner motd ^C ENARSI IPv6 First Hop Security ^C\nvlan 10\n name USERS\n\
    vlan 20\n name SERVERS\nvlan 30\n name GUEST\nvlan 99\n name MGMT\ninterface range GigabitEthernet0/1-3\n switchport mode\
    \ access\n spanning-tree portfast\nend"
- id: n3
  label: USER
  node_definition: desktop
  x: -420
  y: 220
- id: n4
  label: SERVER
  node_definition: desktop
  x: 420
  y: 220
links:
- id: l0
  n1: n0
  i1: 1
  n2: n1
  i2: 0
- id: l1
  n1: n0
  i1: 2
  n2: n2
  i2: 0
- id: l2
  n1: n1
  i1: 1
  n2: n3
  i2: 0
- id: l3
  n1: n2
  i1: 1
  n2: n4
  i2: 0
